name: Deploy Markdown Post

on:
  repository_dispatch:
    types: [deploy-post]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main # 브랜치 이름을 확인하세요.
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Git Config
        run: |
          git config --global user.email "hongbeom.choe@5minlab.com"
          git config --global user.name "워크플로"

      - name: Decode Markdown File
        run: |
          echo "${{ github.event.client_payload.markdown }}" | base64 --decode > "./_posts/${{ github.event.client_payload.filename }}"

      - name: Commit and Push
        run: |
          git add .
          git commit -m "[워크플로] 새 포스트: ${{ github.event.client_payload.filename }}"
          git push
